version: '3'

services:
  app:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/python_test


  mariadb:
    image: mariadb
    container_name: python_mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=python_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  python-app:
    container_name: python_latest
    build: .
    volumes:
      - ./src:/usr/src/./main.py
    depends_on:
      - app
      - mariadb
